package com.eth.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTronAddress<M extends BaseTronAddress<M>> extends Model<M> implements IBean {

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setBalance(java.lang.String balance) {
		set("balance", balance);
	}
	
	public java.lang.String getBalance() {
		return getStr("balance");
	}

	public void setPower(java.lang.String power) {
		set("power", power);
	}
	
	public java.lang.String getPower() {
		return getStr("power");
	}

	public void setDateCreated(java.util.Date dateCreated) {
		set("dateCreated", dateCreated);
	}
	
	public java.util.Date getDateCreated() {
		return get("dateCreated");
	}

	public void setDateUpdate(java.util.Date dateUpdate) {
		set("dateUpdate", dateUpdate);
	}
	
	public java.util.Date getDateUpdate() {
		return get("dateUpdate");
	}

}
