package com.eth.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTronBlock<M extends BaseTronBlock<M>> extends Model<M> implements IBean {

	public void setNumber(java.lang.Long number) {
		set("number", number);
	}
	
	public java.lang.Long getNumber() {
		return getLong("number");
	}

	public void setHash(java.lang.String hash) {
		set("hash", hash);
	}
	
	public java.lang.String getHash() {
		return getStr("hash");
	}

	public void setSize(java.lang.Long size) {
		set("size", size);
	}
	
	public java.lang.Long getSize() {
		return getLong("size");
	}

	public void setTimestamp(java.util.Date timestamp) {
		set("timestamp", timestamp);
	}
	
	public java.util.Date getTimestamp() {
		return get("timestamp");
	}

	public void setTxTrieRoot(java.lang.String txTrieRoot) {
		set("txTrieRoot", txTrieRoot);
	}
	
	public java.lang.String getTxTrieRoot() {
		return getStr("txTrieRoot");
	}

	public void setParentHash(java.lang.String parentHash) {
		set("parentHash", parentHash);
	}
	
	public java.lang.String getParentHash() {
		return getStr("parentHash");
	}

	public void setWitnessId(java.lang.Integer witnessId) {
		set("witnessId", witnessId);
	}
	
	public java.lang.Integer getWitnessId() {
		return getInt("witnessId");
	}

	public void setWitnessAddress(java.lang.String witnessAddress) {
		set("witnessAddress", witnessAddress);
	}
	
	public java.lang.String getWitnessAddress() {
		return getStr("witnessAddress");
	}

	public void setNrOfTrx(java.lang.Integer nrOfTrx) {
		set("nrOfTrx", nrOfTrx);
	}
	
	public java.lang.Integer getNrOfTrx() {
		return getInt("nrOfTrx");
	}

	public void setConfirmed(java.lang.Boolean confirmed) {
		set("confirmed", confirmed);
	}
	
	public java.lang.Boolean getConfirmed() {
		return get("confirmed");
	}

}
