package com.eth.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTronTokenAddres<M extends BaseTronTokenAddres<M>> extends Model<M> implements IBean {

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setBalance(java.lang.String balance) {
		set("balance", balance);
	}
	
	public java.lang.String getBalance() {
		return getStr("balance");
	}

}
