package com.eth.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEthToken<M extends BaseEthToken<M>> extends Model<M> implements IBean {

	public void setTokenAddress(java.lang.String tokenAddress) {
		set("token_address", tokenAddress);
	}
	
	public java.lang.String getTokenAddress() {
		return getStr("token_address");
	}

	public void setTokenName(java.lang.String tokenName) {
		set("token_name", tokenName);
	}
	
	public java.lang.String getTokenName() {
		return getStr("token_name");
	}

	public void setTokenSymbol(java.lang.String tokenSymbol) {
		set("token_symbol", tokenSymbol);
	}
	
	public java.lang.String getTokenSymbol() {
		return getStr("token_symbol");
	}

	public void setTokenDecimals(java.lang.String tokenDecimals) {
		set("token_decimals", tokenDecimals);
	}
	
	public java.lang.String getTokenDecimals() {
		return getStr("token_decimals");
	}

	public void setTokenTotalsupply(java.lang.String tokenTotalsupply) {
		set("token_totalSupply", tokenTotalsupply);
	}
	
	public java.lang.String getTokenTotalsupply() {
		return getStr("token_totalSupply");
	}

	public void setTokenHolders(java.lang.String tokenHolders) {
		set("token_holders", tokenHolders);
	}
	
	public java.lang.String getTokenHolders() {
		return getStr("token_holders");
	}

	public void setTokenTransfers(java.lang.String tokenTransfers) {
		set("token_transfers", tokenTransfers);
	}
	
	public java.lang.String getTokenTransfers() {
		return getStr("token_transfers");
	}

}
