package com.eth.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEthAddressType<M extends BaseEthAddressType<M>> extends Model<M> implements IBean {

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setContractFlag(java.lang.String ContractFlag) {
		set("ContractFlag", ContractFlag);
	}
	
	public java.lang.String getContractFlag() {
		return getStr("ContractFlag");
	}

	public void setErc20Flag(java.lang.String Erc20Flag) {
		set("Erc20Flag", Erc20Flag);
	}
	
	public java.lang.String getErc20Flag() {
		return getStr("Erc20Flag");
	}

	public void setValue(java.lang.String value) {
		set("value", value);
	}
	
	public java.lang.String getValue() {
		return getStr("value");
	}

}
