package com.eth.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEthTokenAddress<M extends BaseEthTokenAddress<M>> extends Model<M> implements IBean {

	public void setTokenAddress(java.lang.String tokenAddress) {
		set("token_address", tokenAddress);
	}
	
	public java.lang.String getTokenAddress() {
		return getStr("token_address");
	}

	public void setTokenHoldAddress(java.lang.String tokenHoldAddress) {
		set("token_hold_address", tokenHoldAddress);
	}
	
	public java.lang.String getTokenHoldAddress() {
		return getStr("token_hold_address");
	}

	public void setTokenHoldValue(java.lang.String tokenHoldValue) {
		set("token_hold_value", tokenHoldValue);
	}
	
	public java.lang.String getTokenHoldValue() {
		return getStr("token_hold_value");
	}

	public void setTokenHoldCreatetime(java.util.Date tokenHoldCreatetime) {
		set("token_hold_createtime", tokenHoldCreatetime);
	}
	
	public java.util.Date getTokenHoldCreatetime() {
		return get("token_hold_createtime");
	}

	public void setTokenHoldUpdatetime(java.util.Date tokenHoldUpdatetime) {
		set("token_hold_updatetime", tokenHoldUpdatetime);
	}
	
	public java.util.Date getTokenHoldUpdatetime() {
		return get("token_hold_updatetime");
	}

}
