package com.eth.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTbcTx<M extends BaseTbcTx<M>> extends Model<M> implements IBean {

	public void setHash(java.lang.String hash) {
		set("hash", hash);
	}
	
	public java.lang.String getHash() {
		return getStr("hash");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setTimestampSubmit(java.lang.String timestampSubmit) {
		set("timestamp_submit", timestampSubmit);
	}
	
	public java.lang.String getTimestampSubmit() {
		return getStr("timestamp_submit");
	}

	public void setTimestamp(java.lang.String timestamp) {
		set("timestamp", timestamp);
	}
	
	public java.lang.String getTimestamp() {
		return getStr("timestamp");
	}

	public void setBlockHash(java.lang.String blockHash) {
		set("blockHash", blockHash);
	}
	
	public java.lang.String getBlockHash() {
		return getStr("blockHash");
	}

	public void setBlockNumber(java.math.BigInteger blockNumber) {
		set("blockNumber", blockNumber);
	}
	
	public java.math.BigInteger getBlockNumber() {
		return get("blockNumber");
	}

	public void setFrom(java.lang.String from) {
		set("from", from);
	}
	
	public java.lang.String getFrom() {
		return getStr("from");
	}

	public void setGas(java.math.BigInteger gas) {
		set("gas", gas);
	}
	
	public java.math.BigInteger getGas() {
		return get("gas");
	}

	public void setGasPrice(java.math.BigInteger gasPrice) {
		set("gasPrice", gasPrice);
	}
	
	public java.math.BigInteger getGasPrice() {
		return get("gasPrice");
	}

	public void setNonce(java.lang.String nonce) {
		set("nonce", nonce);
	}
	
	public java.lang.String getNonce() {
		return getStr("nonce");
	}

	public void setR(java.lang.String r) {
		set("r", r);
	}
	
	public java.lang.String getR() {
		return getStr("r");
	}

	public void setS(java.lang.String s) {
		set("s", s);
	}
	
	public java.lang.String getS() {
		return getStr("s");
	}

	public void setTo(java.lang.String to) {
		set("to", to);
	}
	
	public java.lang.String getTo() {
		return getStr("to");
	}

	public void setV(java.lang.String v) {
		set("v", v);
	}
	
	public java.lang.String getV() {
		return getStr("v");
	}

	public void setValue(java.lang.String value) {
		set("value", value);
	}
	
	public java.lang.String getValue() {
		return getStr("value");
	}

	public void setTbcfrom(java.lang.String tbcfrom) {
		set("tbcfrom", tbcfrom);
	}
	
	public java.lang.String getTbcfrom() {
		return getStr("tbcfrom");
	}

	public void setTbcto(java.lang.String tbcto) {
		set("tbcto", tbcto);
	}
	
	public java.lang.String getTbcto() {
		return getStr("tbcto");
	}

	public void setTbcvalue(java.lang.String tbcvalue) {
		set("tbcvalue", tbcvalue);
	}
	
	public java.lang.String getTbcvalue() {
		return getStr("tbcvalue");
	}

}
