package com.eth.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTronTxFrozen<M extends BaseTronTxFrozen<M>> extends Model<M> implements IBean {

	public void setHash(java.lang.String hash) {
		set("hash", hash);
	}
	
	public java.lang.String getHash() {
		return getStr("hash");
	}

	public void setOwnerAddress(java.lang.String ownerAddress) {
		set("ownerAddress", ownerAddress);
	}
	
	public java.lang.String getOwnerAddress() {
		return getStr("ownerAddress");
	}

	public void setFrozenBalance(java.lang.String frozenBalance) {
		set("frozenBalance", frozenBalance);
	}
	
	public java.lang.String getFrozenBalance() {
		return getStr("frozenBalance");
	}

	public void setFrozenDuration(java.lang.String frozenDuration) {
		set("frozenDuration", frozenDuration);
	}
	
	public java.lang.String getFrozenDuration() {
		return getStr("frozenDuration");
	}

}
