package com.eth.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTronTxVotes<M extends BaseTronTxVotes<M>> extends Model<M> implements IBean {

	public void setHash(java.lang.String hash) {
		set("hash", hash);
	}
	
	public java.lang.String getHash() {
		return getStr("hash");
	}

	public void setNumber(java.lang.Long number) {
		set("number", number);
	}
	
	public java.lang.Long getNumber() {
		return getLong("number");
	}

	public void setVoteAddress(java.lang.String voteAddress) {
		set("voteAddress", voteAddress);
	}
	
	public java.lang.String getVoteAddress() {
		return getStr("voteAddress");
	}

	public void setVoteCount(java.lang.String voteCount) {
		set("voteCount", voteCount);
	}
	
	public java.lang.String getVoteCount() {
		return getStr("voteCount");
	}

}
