package com.eth.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEthAddress<M extends BaseEthAddress<M>> extends Model<M> implements IBean {

	public void setEthAddress(java.lang.String ethAddress) {
		set("eth_address", ethAddress);
	}
	
	public java.lang.String getEthAddress() {
		return getStr("eth_address");
	}

	public void setEthHoldValue(java.lang.String ethHoldValue) {
		set("eth_hold_value", ethHoldValue);
	}
	
	public java.lang.String getEthHoldValue() {
		return getStr("eth_hold_value");
	}

	public void setEthHoldCreatetime(java.util.Date ethHoldCreatetime) {
		set("eth_hold_createtime", ethHoldCreatetime);
	}
	
	public java.util.Date getEthHoldCreatetime() {
		return get("eth_hold_createtime");
	}

	public void setEthHoldUpdatetime(java.util.Date ethHoldUpdatetime) {
		set("eth_hold_updatetime", ethHoldUpdatetime);
	}
	
	public java.util.Date getEthHoldUpdatetime() {
		return get("eth_hold_updatetime");
	}

}
