package com.eth.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTronTxTran<M extends BaseTronTxTran<M>> extends Model<M> implements IBean {

	public void setHash(java.lang.String hash) {
		set("hash", hash);
	}
	
	public java.lang.String getHash() {
		return getStr("hash");
	}

	public void setTranFrom(java.lang.String tranFrom) {
		set("tran_from", tranFrom);
	}
	
	public java.lang.String getTranFrom() {
		return getStr("tran_from");
	}

	public void setTranTo(java.lang.String tranTo) {
		set("tran_to", tranTo);
	}
	
	public java.lang.String getTranTo() {
		return getStr("tran_to");
	}

	public void setTranValue(java.lang.String tranValue) {
		set("tran_value", tranValue);
	}
	
	public java.lang.String getTranValue() {
		return getStr("tran_value");
	}

}
