package com.eth.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEthTx<M extends BaseEthTx<M>> extends Model<M> implements IBean {

	public void setHash(java.lang.String hash) {
		set("hash", hash);
	}
	
	public java.lang.String getHash() {
		return getStr("hash");
	}

	public void setTimestamp(java.lang.String timestamp) {
		set("timestamp", timestamp);
	}
	
	public java.lang.String getTimestamp() {
		return getStr("timestamp");
	}

	public void setBlockHash(java.lang.String blockHash) {
		set("blockHash", blockHash);
	}
	
	public java.lang.String getBlockHash() {
		return getStr("blockHash");
	}

	public void setBlockNumber(java.lang.String blockNumber) {
		set("blockNumber", blockNumber);
	}
	
	public java.lang.String getBlockNumber() {
		return getStr("blockNumber");
	}

	public void setFromAddress(java.lang.String fromAddress) {
		set("from_address", fromAddress);
	}
	
	public java.lang.String getFromAddress() {
		return getStr("from_address");
	}

	public void setToAddress(java.lang.String toAddress) {
		set("to_address", toAddress);
	}
	
	public java.lang.String getToAddress() {
		return getStr("to_address");
	}

	public void setGas(java.lang.String gas) {
		set("gas", gas);
	}
	
	public java.lang.String getGas() {
		return getStr("gas");
	}

	public void setGasPrice(java.lang.String gasPrice) {
		set("gasPrice", gasPrice);
	}
	
	public java.lang.String getGasPrice() {
		return getStr("gasPrice");
	}

	public void setNonce(java.lang.String nonce) {
		set("nonce", nonce);
	}
	
	public java.lang.String getNonce() {
		return getStr("nonce");
	}

	public void setR(java.lang.String r) {
		set("r", r);
	}
	
	public java.lang.String getR() {
		return getStr("r");
	}

	public void setS(java.lang.String s) {
		set("s", s);
	}
	
	public java.lang.String getS() {
		return getStr("s");
	}

	public void setV(java.lang.String v) {
		set("v", v);
	}
	
	public java.lang.String getV() {
		return getStr("v");
	}

	public void setValue(java.lang.String value) {
		set("value", value);
	}
	
	public java.lang.String getValue() {
		return getStr("value");
	}

	public void setBlockDate(java.util.Date blockDate) {
		set("block_date", blockDate);
	}
	
	public java.util.Date getBlockDate() {
		return get("block_date");
	}

}
