package com.eth.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEthTokenTx<M extends BaseEthTokenTx<M>> extends Model<M> implements IBean {

	public void setHash(java.lang.String hash) {
		set("hash", hash);
	}
	
	public java.lang.String getHash() {
		return getStr("hash");
	}

	public void setTokenAddres(java.lang.String tokenAddres) {
		set("token_addres", tokenAddres);
	}
	
	public java.lang.String getTokenAddres() {
		return getStr("token_addres");
	}

	public void setTokenFrom(java.lang.String tokenFrom) {
		set("token_from", tokenFrom);
	}
	
	public java.lang.String getTokenFrom() {
		return getStr("token_from");
	}

	public void setTokenTo(java.lang.String tokenTo) {
		set("token_to", tokenTo);
	}
	
	public java.lang.String getTokenTo() {
		return getStr("token_to");
	}

	public void setTokenValue(java.lang.String tokenValue) {
		set("token_value", tokenValue);
	}
	
	public java.lang.String getTokenValue() {
		return getStr("token_value");
	}

	public void setBlockDate(java.util.Date blockDate) {
		set("block_date", blockDate);
	}
	
	public java.util.Date getBlockDate() {
		return get("block_date");
	}

}
