package com.eth.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTbcTxInter<M extends BaseTbcTxInter<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setValue(java.lang.Long value) {
		set("value", value);
	}
	
	public java.lang.Long getValue() {
		return getLong("value");
	}

	public void setIntro(java.lang.String intro) {
		set("intro", intro);
	}
	
	public java.lang.String getIntro() {
		return getStr("intro");
	}

	public void setFrom(java.lang.String from) {
		set("from", from);
	}
	
	public java.lang.String getFrom() {
		return getStr("from");
	}

	public void setTo(java.lang.String to) {
		set("to", to);
	}
	
	public java.lang.String getTo() {
		return getStr("to");
	}

	public void setTimestamp(java.lang.String timestamp) {
		set("timestamp", timestamp);
	}
	
	public java.lang.String getTimestamp() {
		return getStr("timestamp");
	}

}
