package com.eth.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("eth_address", "eth_address", EthAddress.class);
		arp.addMapping("eth_address_type", "address", EthAddressType.class);
		arp.addMapping("eth_block", "number", EthBlock.class);
		arp.addMapping("eth_token", "token_address", EthToken.class);
		// Composite Primary Key order: token_address,token_hold_address
		arp.addMapping("eth_token_address", "token_address,token_hold_address", EthTokenAddress.class);
		arp.addMapping("eth_token_tx", "hash", EthTokenTx.class);
		arp.addMapping("eth_tx", "hash", EthTx.class);
		arp.addMapping("lynx_user", "user_id", LynxUser.class);
		arp.addMapping("tbc_address", "address", TbcAddress.class);
		arp.addMapping("tbc_tx", "hash", TbcTx.class);
		arp.addMapping("tbc_tx_inter", "id", TbcTxInter.class);
		arp.addMapping("tron_address", "address", TronAddress.class);
		arp.addMapping("tron_block", "number", TronBlock.class);
		// Composite Primary Key order: address,name
		arp.addMapping("tron_token_addres", "address,name", TronTokenAddres.class);
		arp.addMapping("tron_tx", "hash", TronTx.class);
		arp.addMapping("tron_tx_frozen", "hash", TronTxFrozen.class);
		arp.addMapping("tron_tx_token_tran", "hash", TronTxTokenTran.class);
		arp.addMapping("tron_tx_tran", "hash", TronTxTran.class);
		// Composite Primary Key order: hash,number
		arp.addMapping("tron_tx_votes", "hash,number", TronTxVotes.class);
	}
}

