package com.eth.model;

import com.eth.model.base.BaseEthAddressType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EthAddressType extends BaseEthAddressType<EthAddressType> {
	public static final EthAddressType dao = new EthAddressType().dao();
}
