package com.eth.model;

import java.util.List;

import com.eth.model.base.BaseEthToken;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EthToken extends BaseEthToken<EthToken> {
	public static final EthToken dao = new EthToken().dao();

	public Page<EthToken> getTokensPage(int n, int size) {
		return paginate(n, size, "select *", "from eth_token");
	}

	public Page<EthTokenTx> getEthTokenTxsPage(int n, int size) {
		return EthTokenTx.dao.paginate(n, size, "select *", "from eth_token_tx where token_addres = ?", getTokenAddress());
	}

	public EthTokenAddress getHoldersNum() {
		return EthTokenAddress.dao.findFirst("select count(token_hold_address) as num from eth_token_address where token_address = ?", getTokenAddress());
	}

	public List<EthTokenAddress> getHolderAddress() {
		return EthTokenAddress.dao.find("select * from eth_token_address where token_address = ? order by (token_hold_value+0) desc limit 0,50", getTokenAddress());
	}

	public Page<EthTokenAddress> getHolderAllAddress(int n, int size) {
		return EthTokenAddress.dao.paginate(n, size, "select * "," from eth_token_address where token_address = ? order by (token_hold_value+0) desc", getTokenAddress());
	}
}
