package com.eth.model;

import com.eth.model.base.BaseEthTokenAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EthTokenAddress extends BaseEthTokenAddress<EthTokenAddress> {
	public static final EthTokenAddress dao = new EthTokenAddress().dao();
}
