package com.eth.model;

import com.eth.model.base.BaseEthTokenTx;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EthTokenTx extends BaseEthTokenTx<EthTokenTx> {
	public static final EthTokenTx dao = new EthTokenTx().dao();
}
