package com.eth.model;

import java.util.List;

import com.eth.model.base.BaseLynxUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LynxUser extends BaseLynxUser<LynxUser> {
	public static final LynxUser dao = new LynxUser().dao();
	public LynxUser findByUsername(String username){
		return findFirst("select * from lynx_user where user_name = ?", username);
	}
	public LynxUser findByWechat(String unionid){
		return findFirst("select * from lynx_user where wechat = ?", unionid);
	}
	public Boolean usernameExist(String username){
		return findByUsername(username)!=null;
	}
	public List<LynxUser> findAll(){
		return find("select * from lynx_user");
	}
}
