package com.eth.model;

import java.util.List;
import java.util.Map;

import com.eth.model.base.BaseTbcTxInter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbcTxInter extends BaseTbcTxInter<TbcTxInter> {
	public static final TbcTxInter dao = new TbcTxInter().dao();
	private String time = null;
	private String periodTime = null;
	public String getTime(){
		if(getTimestamp()!=null){
			time = LynxUtil.formatDuring(Long.parseLong(getTimestamp()));
		}
		return time;
	}
	public String getPeriodTime(){
		if(getTimestamp()!=null){
			periodTime = LynxUtil.format(Long.parseLong(getTimestamp()));
		}
		return periodTime;
	}
	@Override
	protected Map<String, Object> _getAttrs(){
		Map<String, Object> attrs = super._getAttrs();
		attrs.put("time", this.getTime());
		attrs.put("periodTime", this.getPeriodTime());
		return attrs;
	}
	
	public static void trade(String from, String to, Long value, String intro){
		TbcAddress fromAddr = TbcAddress.dao.findById(from);
		fromAddr.setValue(fromAddr.getValue()-value);
		fromAddr.update();
		TbcAddress toAddr = TbcAddress.dao.findById(to);
		toAddr.setValue(toAddr.getValue()+value);
		toAddr.update();
		TbcTxInter tx = new TbcTxInter();
		tx.setValue(value);
		tx.setFrom(from);
		tx.setTo(to);
		tx.setIntro(intro);
		tx.setTimestamp(String.valueOf(System.currentTimeMillis()/1000));
		tx.save();
	}
	public TbcTxInter getInviteCount(String address){
		return findFirst("select count(1) count, sum(`value`) sum from tbc_tx_inter where `to` = ? and `intro` = '邀请奖励'", address);
	}
	public List<TbcTxInter> getInviteRecord(String address){
		return find("select value, intro, timestamp from tbc_tx_inter where `to` = ? and `intro` = '邀请奖励'", address);
	}
}
