package com.eth.model;

import java.util.Map;

import com.eth.model.base.BaseTbcTx;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbcTx extends BaseTbcTx<TbcTx> {
	public static final TbcTx dao = new TbcTx().dao();
	private String time = null;
	private String periodTime = null;
	public String getTime(){
		if(getTimestamp()!=null){
			time = LynxUtil.formatDuring(Long.parseLong(getTimestamp()));
		}
		return time;
	}
	public String getPeriodTime(){
		if(getTimestamp()!=null){
			periodTime = LynxUtil.format(Long.parseLong(getTimestamp()));
		}
		return periodTime;
	}
	@Override
	protected Map<String, Object> _getAttrs(){
		Map<String, Object> attrs = super._getAttrs();
		attrs.put("time", this.getTime());
		attrs.put("periodTime", this.getPeriodTime());
		return attrs;
	}
}
