package com.eth.model;

import com.eth.model.base.BaseTronTokenAddres;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TronTokenAddres extends BaseTronTokenAddres<TronTokenAddres> {
	public static final TronTokenAddres dao = new TronTokenAddres().dao();
}
