package com.eth.model;

import java.util.List;

import com.eth.model.base.BaseTronTxVotes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TronTxVotes extends BaseTronTxVotes<TronTxVotes> {
	public static final TronTxVotes dao = new TronTxVotes().dao();
	public List<TronTxVotes> findTxVotesByHash(String hash){
		return find("select * from tron_tx_votes where hash = ?", hash);
	}
}
