package com.eth.model;

import java.math.BigDecimal;
import java.util.Map;

import com.eth.model.base.BaseTronTxTran;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TronTxTran extends BaseTronTxTran<TronTxTran> {
	public static final TronTxTran dao = new TronTxTran().dao();
	private BigDecimal minValue = null;
	public BigDecimal getMinValue(){
		if(getStr("tran_value")!=null){
			minValue = new BigDecimal(getStr("tran_value")).divide(new BigDecimal("1000000"));			
		}
		return minValue;
	}
	@Override
	protected Map<String, Object> _getAttrs(){
		Map<String, Object> attrs = super._getAttrs();
		attrs.put("minValue", this.getMinValue());
		return attrs;
	}
}
