package com.eth.model;

import com.eth.model.base.BaseTronTxTokenTran;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TronTxTokenTran extends BaseTronTxTokenTran<TronTxTokenTran> {
	public static final TronTxTokenTran dao = new TronTxTokenTran().dao();
}
