package com.eth.model;

import com.eth.model.base.BaseTronTxFrozen;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TronTxFrozen extends BaseTronTxFrozen<TronTxFrozen> {
	public static final TronTxFrozen dao = new TronTxFrozen().dao();
}
